backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
display_url: https://helping.no
logo_url: https://helping.no/assets/images/logo.svg
slug:
  encoding: 'unicode'
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: 'posts'
    label: 'Artikler'
    folder: '_posts/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Tittel', name: 'title', widget: 'string' }
      - { 
          label: "Forfatter",
          name: "author",
          widget: "relation",
          collection: "author",
          search_fields: ["title"],
          display_fields: ["title"],
          value_field: "_authors/{{slug}}.md",
          required: false 
        }
      - { 
          label: "Med-forfatter",
          name: "coauthor",
          widget: "relation",
          collection: "author",
          search_fields: ["title"],
          display_fields: ["title"],
          value_field: "_authors/{{slug}}.md" ,
          required: false
        }
      - {
          label: "Kategorier",
          name: "categories",
          widget: "relation",
          collection: "category",
          search_fields: ["title"],
          display_fields: ["title"],
          value_field: "_category/{{slug}}.md",
          multiple: true,
          required: false
        }
      - { label: 'Emneknagger', name: "tags", widget: "list", required: false }
      - { label: 'Date', name: 'date', widget: 'hidden' }
      - { label: 'Artikkel Dato', name: 'publish_date', widget: 'datetime', required: false }
      - { label: 'Tittel bilde', name: 'image', widget: 'image', required: false }
      - { label: 'Tilpasse bildet?', name: 'crop_image', widget: 'boolean', hint: 'Setter makshøyde på bildet. La vær å huk av hvis bildet skal vises
    i sin helhet', required: false}
      - { label: 'Ingress', name: 'excerpt', widget: 'string', required: false }
      - { label: 'Bildetekst til tittelbilde', name: 'image_caption', widget: 'string', required: false }
      - { label: 'Weight', name: 'weight', widget: 'number', required: false }
      - { label: 'Innhold', name: 'body', widget: 'markdown', required: false}
  - name: 'author'
    label: 'Forfattere'
    folder: '_authors/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Navn', name: 'title', widget: 'string' }
      - { label: 'Bilde', name: 'image', widget: 'image', required: false }
      - { label: 'Innhold', name: 'body', widget: 'markdown', required: false }
  - name: 'category'
    label: 'Kategori'
    folder: '_category/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'category' }
      - { label: 'Kategorinavn', name: 'title', widget: 'string' }
      - { label: 'Farge', name: 'color', widget: 'color', required: false }
