backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
display_url: https://helping.no
logo_url: https://helping.no/assets/images/logo.svg
collections:
  - name: 'posts'
    label: 'Artikler'
    folder: '_posts/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Tittel', name: 'title', widget: 'string' }
      - { label: "Forfatter", name: "author", widget: "relation", collection: "author", search_fields: ["title"], value_field: "name" }
      - { label: 'Date', name: 'date', widget: 'hidden' }
      - { label: 'Artikkel Dato', name: 'publish_date', widget: 'datetime' }
      - { label: 'Tittel bilde', name: 'image', widget: 'image' }
      - { label: 'Tilpasse bildet?', name: 'crop_image', widget: 'boolean', hint: 'Setter makshøyde på bildet. La vær å huk av hvis bildet skal vises
    i sin helhet'}
      - { label: 'Ingress', name: 'excerpt', widget: 'textarea' }
      - { label: 'Bildetekst til tittelbilde', name: 'image_caption', widget: 'string' }
      - { label: 'Weight', name: 'weight', widget: 'number' }
      - { label: 'Innhold', name: 'body', widget: 'markdown'}
  - name: 'author'
    label: 'Forfattere'
    folder: '_authors/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Navn', name: 'title', widget: 'string' }
      - { label: 'Bilde', name: 'image', widget: 'image' }
      - { label: 'Innhold', name: 'body', widget: 'markdown' }
  - name: 'category'
    label: 'Kategori'
    folder: '_category/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'category' }
      - { label: 'Kategorinavn', name: 'title', widget: 'string' }
      - { label: 'Farge', name: 'color', widget: 'color' }
